name = "ReefGuideWorkerTemplate"
uuid = "bfbf1be7-3acf-4d22-85ac-d1a66a717289"
authors = ["Peter Baker", "Takuya Iwanaga", "Arlo White"]
version = "0.1.0"

[deps]
AWS = "fbe9abb3-538b-5e4e-ba9e-bc94f4f92ebc"
AWSS3 = "1c724243-ef5b-51ab-93f4-b0a88ac62a95"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DotEnv = "4dc1fcf4-5e3b-5448-94ab-0c38ec0385c1"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
JSONWebTokens = "9b8beb19-0777-58c6-920b-28f749fee4d3"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Minio = "4281f0d9-7ae0-406e-9172-b7277c1efa20"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
AWS = "1.92.0"
AWSS3 = "0.11.2"
DotEnv = "1.0.0"
JSON3 = "1.14.2"
Logging = "1.11.0"
Minio = "0.2.2"
Random = "1.11.0"
